# Website Basic Information
baseURL = "https://bloglt.athenalarm.com/"    # Placeholder URL, change to Cloudflare Pages URL after deployment
title = "Athenalarm Tinklaraštis"
languageCode = "lt"
theme = "ananke"

# Author Information (optional)
[author]
  name = "Athenalarm"
  email = "info@athenalarm.com"

# Website Menu (optional)
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Pagrindinis"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "Įrašai"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "Kontaktai"
    url = "/contact/"
    weight = 3

# ---------------------------
# Home Page Settings
# ---------------------------
paginate = 5          # Pagrindiniame puslapyje rodoma naujausių 5 įrašų
mainSections = ["posts"]  # Pagrindiniame puslapyje rodomi tik tipo "posts" įrašai