# Website Basic Information
baseURL = "https://blogmn.athenalarm.com/"    # Placeholder URL, change to Cloudflare Pages URL after deployment
title = "Athenalarm блог"
languageCode = "mn"
theme = "ananke"

# Author Information (optional)
[author]
  name = "Athenalarm"
  email = "info@athenalarm.com"

# Website Menu (optional)
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Нүүр"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "Нийтлэлүүд"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "Холбоо барих"
    url = "/contact/"
    weight = 3

# ---------------------------
# Home Page Settings
# ---------------------------
paginate = 5          # Homepage displays the latest 5 articles
mainSections = ["posts"]  # Home page displays only articles of type "posts"