# Website Basic Information
baseURL = "https://blogka.athenalarm.com/"    # Placeholder URL, change to Cloudflare Pages URL after deployment
title = "Athenalarm ბლოგი"
languageCode = "ka"
theme = "ananke"

# Author Information (optional)
[author]
  name = "Athenalarm"
  email = "info@athenalarm.com"

# Website Menu (optional)
[menu]
  [[menu.main]]
    identifier = "home"
    name = "მთავარი"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "პოსტები"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "კონტაქტი"
    url = "/contact/"
    weight = 3

# ---------------------------
# Home Page Settings
# ---------------------------
paginate = 5          # მთავარი გვერდი აჩვენებს ბოლო 5 პოსტს
mainSections = ["posts"]  # მთავარი გვერდი აჩვენებს მხოლოდ type = "posts" პოსტებს